[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["newsapi_headlines_to_email"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/ManualTrigger","Category/Integration"]
  name = "newsapi_headlines_to_email"
  org = "sadeepapalliyaguru"
  version = "3.1.0"

